version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
  
  backend:
    image: adwxith/speakex-backend:latest
    container_name: backend
    ports:
      - '5000:5000'
    env_file:
      - .env
    depends_on:
      - redis
